### PR TITLE
Fix to work on modern browsers + locally + make example protocol agnostic

### PR DESCRIPTION
**Pull request by samyk**

### CODE REVIEW

**Comment by 43081j** [comment]
sorry for being slow at having a look at this.

blast from the past! this repo has been stale for some time, thank you for the contribution. ill try it out myself then get it merged 👍

**Comment by 43081j** [comment]
whats going on with this minified JS? it has a typo in it and a broken block of code around one of the for loops.

should be generated in CI, i know, but also wondering how/why it ended up like that

**Comment by samyk** [comment]
How are you testing the minified JS? I swapped out the <script> in the example/index.html and tested on Chrome (Beta) 88.0.4324.50 on an https host with no issue. 

```
tigerblood:/Users/samy/code/openspec/funky$ minify -v
v6.0.1
tigerblood:/Users/samy/code/openspec/funky$ minify dist/funky.js > funky.min.js
tigerblood:/Users/samy/code/openspec/funky$ sha256sum funky.min.js
dc2e9aed70ba2c2d3440e218fa4c0c8537729867e555190a664e8c122f2fb30e  funky.min.js
```

**Comment by 43081j** [comment]
i had another look, it seems the old version might have been wrong in the first place. some funky minification going on in `master` so i think you indirectly fixed it 😂 

no worries, will get it merged later if i can

**Pull request merged**
